# Generated by Django 5.2.2 on 2025-06-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principallogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailName', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('studentNumber', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('courses', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Phone', models.CharField(max_length=15)),
                ('ID_number', models.CharField(max_length=20, unique=True)),
                ('TeacherNumber', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Unit', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('DateHired', models.DateField()),
            ],
        ),
    ]
