# Generated by Django 5.1.5 on 2025-07-03 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Location', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=255)),
                ('Receiver', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('DateSent', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Principallogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmailName', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('studentNumber', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('courses', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Phone', models.CharField(max_length=15)),
                ('ID_number', models.CharField(max_length=20, unique=True)),
                ('TeacherNumber', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Unit', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('DateHired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Hub.teacherdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Students', models.CharField(max_length=255)),
                ('Schedule', models.DateField()),
                ('Status', models.CharField(max_length=255)),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hub.teacherdetails')),
            ],
        ),
    ]
