# Generated by Django 5.2.2 on 2025-06-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Teacher', models.CharField(max_length=255)),
                ('Students', models.CharField(max_length=255)),
                ('Schedule', models.DateField()),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
    ]
