# Generated by Django 5.1.5 on 2025-07-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('class_name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active')], max_length=50)),
                ('submitted', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/')),
            ],
        ),
    ]
