# Generated by Django 5.2.2 on 2025-06-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0002_coursetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Date', models.TextField()),
                ('Time', models.TimeField()),
                ('Location', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
            ],
        ),
    ]
