# Generated by Django 5.2.2 on 2025-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0002_studenttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherNumber', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
