# Generated by Django 5.2.2 on 2025-08-18 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
