# Generated by Django 5.2.2 on 2025-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0003_eventtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtable',
            name='Date',
            field=models.DateField(),
        ),
    ]
