# Generated by Django 5.2.2 on 2025-08-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0004_activitylog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetable',
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='coursetable',
            name='Students',
        ),
        migrations.RemoveField(
            model_name='coursetable',
            name='Teacher',
        ),
    ]
