# Generated by Django 5.1.5 on 2025-08-25 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0006_lessonschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonschedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lessonschedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lessonschedule',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=django.utils.timezone.now, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='unit',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
