# Generated by Django 5.1.5 on 2025-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0007_remove_lessonschedule_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonschedule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
