# Generated by Django 5.2.2 on 2025-08-26 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0008_lessonschedule_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='Hub.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Hub.teacherdetails'),
        ),
    ]
